name = "pdf-converter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
workers_dev = false
route = "4renpk.my/*"

[triggers]
crons = []
