name = "pdf-to-word-converter"
main = "app.py"
compatibility_date = "2024-01-01"

[build]
command = "pip install -r requirements.txt"

[vars]
PYTHONPATH = "."

[[rules]]
type = "ESModule"
globs = ["**/*.py"]

[env.production]
workers_dev = false

[[routes]]
pattern = "4renpk.my/*"
zone_id = "32de47583b6619039eeef111d4896fb0" 
